# Generated by Django 3.1.4 on 2021-01-16 18:07

import autoslug.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='user', slugify=profiles.models.custom_slugify, unique_with=['user'])),
                ('profile_pic', models.ImageField(blank=True, default='profile/male_jmfdfj.svg', upload_to='profile/')),
                ('bio', models.TextField(blank=True, max_length='200', null=True)),
                ('country', django_countries.fields.CountryField(default='IN', max_length=2)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('date_of_birth', models.DateField(blank=True, default=datetime.date(1997, 10, 19), null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profiles',
                'verbose_name_plural': 'Profiles',
                'ordering': ['-created_on'],
            },
        ),
    ]
