# Generated by Django 3.1.4 on 2021-01-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='profile_pic',
            field=models.ImageField(default='profile/male.svg', upload_to='profile/'),
        ),
    ]
